### PR TITLE
Few changes to get better readability and content parsing

### PR DESCRIPTION
**Pull request by ArxdSilva**
things in this PR:
1) Moved Track struct;
2) Removed `end` func;
3) Added error handling to main.go

Explanations:
1) We need to work with it since the beginning, to prevent content parsing and complex structures;
2) not necessary anymore;
3) It's really important to check It always, this way you prevent debugging all time with prints, cause you get exactly where It's wrong;

Obs: 
- CLI might not be working (didn't check), but the code is essentially the same.
- It'll help a lot If you use TDD on every package, so you'll get everything working before the whole thing gets together.
- If you want an example of xml package - I did a CLI package a while ago that manipulates `xml` files, reads and writes into It called [XML-Comp](https://github.com/xml-comp/XML-Comp/).

### CODE REVIEW

**Comment by ibrokemypie** [comment]
Thsanks for this! I have been working through it trying to get the xml part to work, think its close. I have removed error handling for m3u/lookupargs since the location string can always be given, so missing or unreadable files are not our problem. After the xspf/makexml is working I am going to redo main to use flags, and with a verbose flag the errors will be shown.

**Comment by ArxdSilva** [comment]
@ibrokemypie I can help you with tests and getting It together soon, just need some time to lookup more how you're doing things on xspf/makexml cause all I did was on the fly. Until next week I'll make some tests and add to this PR so you can get certain that It's really working.

**Comment by ibrokemypie** [comment]
Heres what i am working on right now.
One of the benefits of xspf is that it can work both as a dumb format (eg m3u, just point to a file) or as smart with metadata. Missing files are not our concern, we will still add them as an entry with just their location, and potentially hundreds could be missing, so dont want to spam the stdout unless the user wants it.

The trackMap has been changed to a slice, since we dont actually need to map each map to anything, just store each map of strings. Right now I am just stuck on how to generate an xml with format playlist>tracklist>each track in trackmap>attributes of that track

[diff.txt](https://github.com/ibrokemypie/m3uspiff_go/files/991598/diff.txt)

**Comment by ibrokemypie** [comment]
```
diff --git a/example.m3u b/example.m3u
index 036f8e8..b13787e 100644
--- a/example.m3u
+++ b/example.m3u
@@ -2,10 +2,10 @@
 #EXTM3U
 
 #EXTINF:123, Sample artist - Sample title
-#Sample.mp3
+Sample.mp3
 
 #EXTINF:321,Example Artist - Example title
-#Greatest Hits\Example.ogg
+Greatest Hits\Example.ogg
 
 #EXTINF:321,Example Artist - Example title
 #/Volumes/extDISK/music/Coldplay/Parachutes/01 Don't Panic.mp3
diff --git a/m3u/lookupargs.go b/m3u/lookupargs.go
index dd621e4..f82fcf8 100644
--- a/m3u/lookupargs.go
+++ b/m3u/lookupargs.go
@@ -1,41 +1,34 @@
 package m3u
 
 import (
+	"github.com/dhowden/tag"
 	"os"
 	"strconv"
-
-	"github.com/dhowden/tag"
 )
 
-type Track struct {
-	Creator  string `xml:"creator,omitempty"`
-	Album    string `xml:"album,omitempty"`
-	Title    string `xml:"title,omitempty"`
-	TrackNum string `xml:"trackNum,omitempty"`
-	Location string `xml:"location"`
-	Entry    string
-}
+type Track map[string]string
 
-var entries = 0
+var entry Track
 
-func Lookupargs(line string) (*Track, error) {
+func Lookupargs(line string) (Track, error) {
 	file, err := os.Open(line)
-	if err != nil {
-		return nil, err
-	}
-	tagf, err := tag.ReadFrom(file)
-	if err != nil {
-		return nil, err
-	}
-	track, _ := tagf.Track()
-	entry := Track{
-		Creator:  tagf.Artist(),
-		Album:    tagf.Album(),
-		Title:    tagf.Title(),
-		TrackNum: strconv.Itoa(track),
-		Entry:    strconv.Itoa(entries),
-		Location: line,
+	if err == nil {
+		tagf, err := tag.ReadFrom(file)
+		if err == nil {
+			tracknum, _ := tagf.Track()
+			entry = Track{
+				"Location": line,
+				"Title":    tagf.Title(),
+				"Creator":  tagf.Artist(),
+				"Album":    tagf.Album(),
+				"TrackNum": strconv.Itoa(tracknum),
+			}
+		}
+	} else {
+		//Don't panic if the file isnt there or can't be read, just write location then
+		entry = Track{
+			"Location": line,
+		}
 	}
-	entries++
-	return &entry, err
+	return entry, err
 }
diff --git a/m3uspiff_go b/m3uspiff_go
index 5f6dd86..c485158 100755
Binary files a/m3uspiff_go and b/m3uspiff_go differ
diff --git a/main.go b/main.go
index 14dd186..cfca9c0 100644
--- a/main.go
+++ b/main.go
@@ -4,14 +4,12 @@ import (
 	"errors"
 	"fmt"
 	"os"
-	"strconv"
 
 	"github.com/ibrokemypie/m3uspiff_go/m3u"
 	"github.com/ibrokemypie/m3uspiff_go/xspf"
 )
 
-var trackMap = map[string]*m3u.Track{}
-var entries = 0
+var trackMap = []m3u.Track{}
 
 func main() {
 	if len(os.Args) != 2 {
@@ -24,19 +22,17 @@ func main() {
 	if err != nil {
 		panic(err)
 	}
+
 	m3u.Parsem3u(file)
 	for _, line := range m3u.Lines {
-		entry, errLookup := m3u.Lookupargs(line)
-		if errLookup != nil {
-			panic(errLookup)
-		}
-		trackMap[strconv.Itoa(entries)] = entry
-		entries++
+		entries, _ := m3u.Lookupargs(line)
+		trackMap = append(trackMap, entries)
 	}
 
 	err = xspf.Makexml(trackMap)
 	if err != nil {
 		panic(err)
 	}
+	fmt.Println(xspf.Output.String())
 	os.Exit(0)
 }
diff --git a/test b/test
new file mode 100755
index 0000000..3f58662
--- /dev/null
+++ b/test
@@ -0,0 +1,3 @@
+#!/bin/bash
+go build
+./m3uspiff_go example.m3u
diff --git a/xspf/makexml.go b/xspf/makexml.go
index 4f84e0b..a2c6064 100644
--- a/xspf/makexml.go
+++ b/xspf/makexml.go
@@ -2,34 +2,27 @@ package xspf
 
 import (
 	"bytes"
-	"encoding/xml"
-	"fmt"
-
 	"github.com/ibrokemypie/m3uspiff_go/m3u"
 )
 
-type playlist struct {
-	Tracklist map[string]*m3u.Track `xml:"tracklist"`
-	Version   int                   `xml:"version,attr"`
-	Xmlns     string                `xml:"xmlns,attr"`
-}
-
 var Output bytes.Buffer
 
-func Makexml(trackMap map[string]*m3u.Track) error {
-	Output.WriteString(xml.Header)
-	final := &playlist{
-		Version:   1,
-		Xmlns:     "http://xspf.org/ns/0/",
-		Tracklist: trackMap,
-	}
+func Makexml(trackMap []m3u.Track) error {
+	// The Map
+	var err error
+	Output.WriteString("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
+	Output.WriteString("\n<playlist version=\"1\" xmlns=\"http://xspf.org/ns/0/\">")
+	Output.WriteString("\n	<trackList>")
 
-	oops, err := xml.MarshalIndent(final, "  ", "    ")
-	if err != nil {
-		return err
+	for _, track := range trackMap {
+		Output.WriteString("\n		<track>")
+		for field, value := range track {
+			Output.WriteString("\n			<" + field + ">" + value + "</" + field + ">")
+		}
+		Output.WriteString("\n		</track>")
 	}
+	Output.WriteString("\n	</trackList>")
+	Output.WriteString("\n</playlist>")
 
-	Output.Write(oops)
-	fmt.Println(Output.String())
 	return err
 }

```

**Comment by ibrokemypie** [comment]
closed with #77ad01d

**Pull request merged**
